version: '3'
services:
    back:
        container_name: ${PROJECT_NAME?}_back
        build:
            context: docker
            dockerfile: ./back/Dockerfile
        env_file: .env
        ports:
            - "8080:8080"
        volumes:
            - "./app:/home/projects/ZipAirlines/.www"
        privileged: true
