# Generated by Django 3.2.13 on 2022-04-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.IntegerField(null=True, unique=True, verbose_name='AirplaneID')),
                ('passengers_count', models.IntegerField(null=True, verbose_name='Current passenger load')),
            ],
        ),
    ]
